# Generated by Django 6.0.3 on 2026-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='papers/')),
                ('term', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=7)),
            ],
        ),
    ]
