# Generated by Django 6.0.3 on 2026-05-05 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='record',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='uploaded_by',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
