# Generated by Django 6.0.3 on 2026-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_record_options_record_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
