# Generated by Django 6.0.3 on 2026-05-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='uploaded_email',
            field=models.EmailField(default='anonymous@example.com', max_length=255),
        ),
    ]
