# Generated by Django 6.0.3 on 2026-05-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_record_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
