# Generated by Django 6.0.3 on 2026-05-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_record_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Reported Paper',
                'verbose_name_plural': 'Reported Papers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.record',),
        ),
    ]
