# Generated by Django 6.0.3 on 2026-05-29 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_record_file_alter_record_saved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('term', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='program',
        ),
        migrations.RemoveField(
            model_name='record',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='record',
            name='session',
        ),
        migrations.RemoveField(
            model_name='record',
            name='term',
        ),
        migrations.RemoveField(
            model_name='record',
            name='uni_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='year',
        ),
        migrations.AlterField(
            model_name='record',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='uni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.uni'),
        ),
    ]
