# Generated by Django 6.0.3 on 2026-06-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_course_uni_remove_record_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='session',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='uni',
            name='uni_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('uni', 'semester', 'program', 'course_name', 'year', 'term', 'session')},
        ),
    ]
