# Generated by Django 6.0.3 on 2026-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_course_year_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='uploaded_email',
            field=models.EmailField(db_index=True, default='anonymous@example.com', max_length=255),
        ),
    ]
