# Generated by Django 6.0.3 on 2026-06-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_record_status_alter_record_uploaded_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='file_extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
