# Generated by Django 6.0.3 on 2026-06-18 20:24

import cloudinary_storage.storage
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_record_file_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=home.models.get_upload_path),
        ),
    ]
