# Generated by Django 6.0.3 on 2026-06-18 20:45

import cloudinary_storage.storage
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_record_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=home.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='file',
            field=models.FileField(max_length=500, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=home.models.get_upload_path),
        ),
    ]
